### ISSUE TITLE
Idiomes i traduccions

### ISSUE THREAD

**Issue by Merce5** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#10]
Hola! Hem vist que teniu la taula d'idiomes i les seves relacions amb les modalitats, les obres, els espais i els serveis (pot esser m'en deix qualquna). Ens agradaría que en el moment de fer la petició als espais (per exemple) enlloc de que el json sols tingués una descripció, aquesta descripció fós un array amb objectes descripcions que inclogui l'ID de l'idioma i la seva corresponent traducció. Sería més o menys així:

<pre><code>{
    "id": 3,
    "nom": "El Prado",
    "tipus_id": 1,
    "descripcions": [
        {
            "idioma": 1,
            "traduccio": "Bones, com va?"
        },
        {
            "idioma": 2,
            "traduccio": "Hola! ¿Que tal?"
        },
        {
            "idioma": 3,
            "traduccio": "Hello! What happens?"
        }
    ],
    "localitat": "Madrid",
    "destacat": 6,
    "adreca": "c/larga 3",
    "email": "elprado@gmail.com",
    "web": "www.elprado.com"  
}</code></pre>

**Comment by Joancastell4** [comment]
Bones, afegides les descripcions amb els diferents idiomes al GET d'espais.
