### ISSUE TITLE
Control de errores en el login

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#12]
Se podria poner un mensaje de si el usuario no existe o si esta mal la contraseña a la hora de hacer el login? por favor.

**Comment by AngelLlompart** [comment]
![image](https://user-images.githubusercontent.com/77398966/154295821-a63c07d8-2922-4dd8-947f-80b5c49609c8.png)
Es decir en vez de que ponga status fail, ponga un mensaje diciendo "Ese correo no esta registrado" o si el error es en la contraseña, "La contraseña introducida no coincide" o "La contraseña es erronea". Algo asi

**Comment by Merce5** [comment]
Basta que digui que no es correcte

**Comment by Joancastell4** [comment]
Cambiat el text de resposta quant l'email o contrasenya són incorrectes.
