### ISSUE TITLE
Registarse sin token

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#13]
Estaria bien si se pudiera hacer registro sin token, ya que al querer registrarse se supone que no hay que hacer un login antes. Es decir cuando un usuario no tiene cuenta se tiene que poder registrar.

**Comment by Joancastell4** [comment]
Llevat la necessitat de tenir el token per el registre d'un usuari.
