### ISSUE TITLE
Exposicions_obres

### ISSUE THREAD

**Issue by Merce5** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#15]
Bones, ens agradaría que quan faguem un get d'una exposició en concret, aquest retorni totes les obres que es trobin a aquesta exposició. Per exemple:

<pre><code>{
    "id": 1,
    "espai_id": 4,
    "nom": "Petit Palais",
    "data_inici": "2021-10-04",
    "data_fi": "2021-11-20",
    "obres" : [
        {
            "ID": 1,
            "Títol": "Peinture (Femme, tige, coeur)",
            "Autor": "Miquel Pascual Rosselló",
            "Fotografia": null,
            "Data": "1956-05-21",
            "Descripció": "Pintura colorida, amb visió futurista",
            "Modalitat": "Pintura"
        },
        {
            "ID": 2,
            "Títol": "Peinture (Femme, tige, coeur)",
            "Autor": "Miquel Pascual Rosselló",
            "Fotografia": null,
            "Data": "1956-05-21",
            "Descripció": "Pintura colorida, amb visió futurista",
            "Modalitat": "Pintura"
        },
        {
            "ID": 3,
            "Títol": "Peinture (Femme, tige, coeur)",
            "Autor": "Miquel Pascual Rosselló",
            "Fotografia": null,
            "Data": "1956-05-21",
            "Descripció": "Pintura colorida, amb visió futurista",
            "Modalitat": "Pintura"
        }
    ]
}</code></pre>

D'aquesta manera el programa guanya molt de rendiment.

**Comment by AngelCaballeroDev** [comment]
Bones! Hem modificat s'api i ara ja es mostren totes les obres que hi ha a l'exposició. El problema és que també es mostra la taula intermitja, a més de totes les dades d'autor i de modalitat. Intentarem depurar les dades en la mida de lo possible. Al manco de moment podreu accedir a tota la informació.

**Comment by Merce5** [comment]
Okey, de moment va bé, moltes gràcies
