### ISSUE TITLE
Paràmetres de les obres

### ISSUE THREAD

**Issue by Merce5** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#16]
Hola! La informació de la obra es retorna de 3 maneres diferents.

La primera es quan demanam todes les obres:

![image](https://user-images.githubusercontent.com/77398452/154300621-f963980f-cbf6-486e-8086-f4cf96d33858.png)

Quan demanam les obres de una exposició (actualment no hi ha resposta, veure https://github.com/CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel/issues/15)

I quan es llisten totes les obres:
![image](https://user-images.githubusercontent.com/77398452/154303099-cfd20b5b-e254-464b-b1a9-fbed5061cd3d.png)

Es molt important que els atributs del json tenguin el mateix nom cada vegada que es llisti un objecte del mateix tipus ja que alhora de pasar-lo a objecte programant necessitam que sempre tengui el mateix nom. Preferiblement de la manera en la que hem indicat a la issue https://github.com/CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel/issues/15.

**Comment by AngelCaballeroDev** [comment]
Bon dia! Unificats els paràmetres d'obra.  

Salut!

**Comment by Merce5** [comment]
Bon día, vos heu deixat per afegir l'autor i la modalitat quan es fa la petició de totes les obres i si es rellevant o no quan es fa la petició d'una obra.

Una obra:
![image](https://user-images.githubusercontent.com/77398452/154494423-1ca39557-d61b-4472-89fb-2a4c832e3517.png)

Totes les obres:
![image](https://user-images.githubusercontent.com/77398452/154494506-fd50da38-20cc-4cea-ba0a-daba15326710.png)

Si ho poguessiu corregir quan pogeu... Moltes gràcies.

PD: Hem vaig equivocar quan vaig possar la issue i vos vaig posar el mateix exemple les dues vegades, hem refería a quan feim la petició d'una sola obra, quan feim la petició de les obres d'una exposició i quan feim la petició de totes les obres. Perdó per la confusió.

Salut!

**Comment by AngelCaballeroDev** [comment]
Bones! Ara si, tots el requests d'obres duen tots els atributs de l'autor i la modalitat, a més d'indicar si és rellevant o no.

Salut!
