### ISSUE TITLE
Al fer un login, podria retornar també la id

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#17]
Bones, al fer un login necessitaria que em torni també la id, perquè si no, no hi ha cap manera d'aconseguir les dades d'aquest usuari que s'ha fet login ja que només disposam del email, contrasenya i token, per treure les dades d'un usuari necessitam la id segons el get /usuaris/id.

**Comment by Joancastell4** [comment]
Bones, afegit l'id de l'usuari a la resposta del login.
