### ISSUE TITLE
Comentaris per usuari

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#18]
Bones, necesitariem un get de comentaris per un usuari concret, que ens dongui tots els comentaris que ha fet aquell usuari.

**Comment by Joancastell4** [comment]
Bones, afegida la relació entre usuaris i valoracions. Ara quant faceu un GET d'usuaris podreu veure tot els seus comentaris fets. Si voleu veure tots els comentaris fets per un usuari en concret amb el GET de usuaris/{id} ho podreu veure.
