### ISSUE TITLE
No funciona post usuaris

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#25]
Bon dia, no se perquè no funciona el post d'usuaris si fa uns dies funcionava perfectament.
![image](https://user-images.githubusercontent.com/77398966/155894627-05904fc5-b305-4f78-b246-7b93baf0e7a8.png)

Pot ser sigui algun despist meu pero no trob que hagi posat res malament, per favor arreglau-lo quant abans si el problema es a l'api.
Per cert també necessitam que ens torneu a habilitar poder eliminar usuaris, ja que és un dels requisits.

També m'agradaria si podeu solucionar els issues quant abans degut a que nosaltres hem d'entregar el treball aquest divendres.
Moltes gràcies.

**Comment by AngelCaballeroDev** [comment]
Bon dia! El post d'usuaris ja funciona. També hem llevat ses restriccions per eliminar usuaris.

Salut!
