### ISSUE TITLE
Heu llevat la id del login d'usuari...

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#28]
Necessitam que retorni la id com ja vaig demanar en un issue de fa temps i ho vareu fer, però ho heu tornat a llevar.
![image](https://user-images.githubusercontent.com/77398966/156384599-dd289905-831b-43ff-adfa-49f2a837ea02.png)

**Comment by AngelCaballeroDev** [comment]
Quina id vols que torni i quan? Crec que no entenc que vols dir.

**Comment by AngelCaballeroDev** [comment]
Val, dius quan fas el login. Ara ho tornam arreglar.

**Comment by AngelLlompart** [comment]
Sí, la id de l'usuari que fa login. És una funció que vos vaig demanar fa temps i la vareu cumplir, però no entenc perquè la heu llevada. Gràcies.

**Comment by AngelCaballeroDev** [comment]
Ja la teniu.
