### ISSUE TITLE
Millores a fer

### ISSUE THREAD

**Issue by tcampaner** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#4]
No teniu l'ajuda pujada, ho heu de posar al readme.
Heu de descriure al readme com fer un login url i paràmetres.
Heu de solventar, contestar i tancar els issues.

**Comment by AngelCaballeroDev** [comment]
Ja està pujada l'ajuda  un document pdf juntament amb el readme modificat.  
Corregit l'error als paràmetres per fer el login.  
Issues contestats.  
Actualment esteim treballant en una vista amb l'ajuda per accedir des de l'endpoint principal.
