### ISSUE TITLE
No deja hacer el post del login con las credenciales proporcionadas

### ISSUE THREAD

**Issue by Merce5** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#5]
Cuando intentamos hacer el post desde el postman para obtener el token nos salta el siguiente error:
![image](https://user-images.githubusercontent.com/77398452/153223247-fac47345-9312-4b3a-8af9-aa8f40194513.png)

**Comment by Joancastell4** [comment]
Normal que no funcioni, l'atribut per a la contrasenya és "contrasenya", no password. A n'el Readme esta especificat el nom dels atributs.

**Comment by Joancastell4** [comment]
<img width="757" alt="Captura de pantalla 2022-02-10 a las 15 25 09" src="https://user-images.githubusercontent.com/61620226/153427424-9fda892f-e14b-4a9d-9a5f-dd4daac202ae.png">

**Comment by Merce5** [comment]
Ok, pues s'hauría de canviar la documentació, ja que allà posa password.
![image](https://user-images.githubusercontent.com/77398452/153451655-1082dee7-499a-4ed9-97b7-338178eee518.png)

**Comment by Joancastell4** [comment]
Corregit.
