### ISSUE TITLE
No nos deja hacer login. Status: fail.

### ISSUE THREAD

**Issue by Merce5** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#7]
![image](https://user-images.githubusercontent.com/77398452/153905599-ba0f6a60-45ae-4079-b42c-ae79ec00548b.png)

**Comment by AngelCaballeroDev** [comment]
Eliminasteis algún usuario de la base de datos? No se podía hacer el login porque los usuarios ya no estaban. Ya están restablecidos. Probad a ver.

**Comment by Merce5** [comment]
Borramos 2 usuarios, el 9 y el 10, pero había más y ninguno era el que tenía asignado el correo de prueba (que nosotros sepamos). Lo extraño es que se borraran todos los usuarios.

**Comment by AngelCaballeroDev** [comment]
No no, si el resto de usuarios estaban. Los que faltaban son justo los que habíamos introducido para poder hacer el login. No hay problema, en cualquier caso ya están restablecidos. Ahora en principio no se pueden borrar usuarios. Si en algún momento necesitáis eliminar alguno avisadnos y quitamos la restricción, ok?

**Comment by Merce5** [comment]
Perfecto.
