### ISSUE TITLE
El post d'usuaris funciona com si fos un get

### ISSUE THREAD

**Issue by AngelLlompart** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#8]
He intentat probar d'insertar un usuari per a veure quins valors feien falta (ja que tampoc s'esmenten a la documentació) i resulta que donava igual els valors que poses, tot el rato em posa OK i em torna la llista d'usuaris sense introduïr el nou, fins i tot si el json esta buit:
![image](https://user-images.githubusercontent.com/77398966/153953194-59c322e7-ca64-4897-8dbc-fbe713d24a19.png)

![image](https://user-images.githubusercontent.com/77398966/153953157-5b03ba46-9503-4d31-9862-910ae3ab38da.png)

**Comment by AngelCaballeroDev** [comment]
Bon dia, acabo d'intentar fer un post per crear un usuari tant amb form-urlencoded com amb json i no m'ha donat cap problema
![2022-02-15_10h39_46](https://user-images.githubusercontent.com/77160925/154036789-1a65566f-2cb7-41ce-af3f-7c3617947b6b.png)
:
![2022-02-15_10h46_30](https://user-images.githubusercontent.com/77160925/154036900-a5e34653-41aa-4059-9f18-ef084ed9b620.png)

Pot ser l'errada estigui en que efectivament, a la documentació hi ha un error a nes post d'usuaris que en breu estarà corregit.

**Comment by AngelCaballeroDev** [comment]
Igualment he provat de fer un post amb un JSON buid tal com has fet tu i el resultat és un error de servidor, no un get
![2022-02-15_11h00_09](https://user-images.githubusercontent.com/77160925/154038835-378398a6-fb33-4377-aba1-21d817d2e812.png)
:

**Comment by AngelCaballeroDev** [comment]
Hem comprovat també que els usuaris s'han introduit correctament amb un get:
![2022-02-15_11h03_07](https://user-images.githubusercontent.com/77160925/154039176-23a3ace7-06c4-4ae4-a248-a83ed21d72e7.png)

**Comment by spdvi** [comment]
Hola, si us heu fixat @AngelLlompart fa les peticions a /api/public/api/usuaris/ i @AngelCaballeroDev a /api/public/api/usuaris 
Hi ha molta diferència ja que son endpoints diferents. La / del final es la questió.
La explicació a perquè a @AngelLlompart li surt com si fos un GET /api/public/api/usuaris es què al fer el POST /api/public/api/usuaris/ el servidor retorna un '301 Moved permanently' i Postman el rep i fa automàticament un GET /api/public/api/usuaris.
Per lo tant no es lo mateix .../usuaris que .../usuaris/
A la documentació s'indica que l'endpoint és .../usuaris/. En poder corregiu-lo per favor.
Esper haver-vos ajudat.
Salutacions i gràcies per les vostres contribucions.
