### ISSUE TITLE
Documentació

### ISSUE THREAD

**Issue by Merce5** [CIFP-Pau-Casesnoves-DAW/baleart-public-ana-joanpere-joan-angel#9]
Hem vist que heu arreglat moltes coses de la API, però la documentació està desactualitzada i així com està establerta es difícil comprendre que fa cada cosa. El problema, sobretot, recau en que hi ha coses girades (post i get amb els paràmetres girats).

Podríeu actualitzarla i completar-la de manera que s'entengui que necessita cada petició? Necessitam saber l'estructura de dades per a poder treballar amb elles. Si tinguessiu l'esquema de la base de dades també sería útil ja que será més fácil comprendre el funcionament de la API.

**Comment by spdvi** [comment]
@Merce5 podríes indicar quines coses hi ha girades en concret?
Potser estau fent els requests als endpoints amb la / final com s'indica a la documentació (a corregir), però ho solucionareu si ho feu sense la / al final (p.ex. GET /obres i POST /obres i no POST /obres/).
Veieu #8 per la explicació de perquè passa això.
Salutacions

**Comment by spdvi** [comment]
Respecte a la documentació si es cert que a alguns endpoints falten els paràmetres, com ara a POST .../usuaris
En poder anau actualitzant-la per favor.
Gràcies!

**Comment by Merce5** [comment]
N'hi ha bastantes en tota la documentació. Un exemple es el següent: 
Ens demanen paràmetres per borrar però no per inserir i ja que la taula es idiomes_modalitats no crec que els paràmetres siguin sols un id, en tot cas sería la id de l'idioma i el de la modalitat, pot esser que no sigui així però com que tampoc s'explica, no entenem el fuincionament de quasi cap petició.

![image](https://user-images.githubusercontent.com/77398452/154166054-70052806-d60c-436e-aad8-15b5d1a9af61.png)
![image](https://user-images.githubusercontent.com/77398452/154166082-d2bb0683-7a02-40f6-91a5-d2da2fc2eca9.png)

Un altre exemple es el cas dels idiomes. El get té un paràmetre que es la id tant a la url com al cos, el post no rep cap paràmetre d'id, sols el nom (tal vegada es autoincrement però tampoc ho sabem)

![image](https://user-images.githubusercontent.com/77398452/154166545-5f31afb4-995f-40e4-9326-4634fe173721.png)

Hi ha bastants exemples més però tot recau en el mateix, pot esser s'hagin desordenat o qualsevol cosa, però quasi no s'entenen moltes coses.

**Comment by AngelCaballeroDev** [comment]
Bones!
Ja està corregida la documentació. Millor si accediu a ella des de es pdf que hi ha al repositori (esteim solventant unes incidències amb sa vista). @spdvi tota sa raó amb lo de sa /. No ens haviem adonat de que això podia donar problemes. Ja ho hem rectificat, gràcies! 

En principi totes les rutes responen. Comentar-vos que els id's són autoincrementals, per això no figuren als paràmetres dels POST. Si teniu cap problema informau-nos, ok?

Salut!

**Comment by Merce5** [comment]
Hola! Moltes gràcies, ara s'entén molt més, vos anirem informant si sorgeix qualque dubte o inconvenient.

Salut!
